{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2f38acba",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import zipfile\n",
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "4738c9f2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "data\\Flight Delay Dataset.zip\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>YEAR</th>\n",
       "      <th>QUARTER</th>\n",
       "      <th>MONTH</th>\n",
       "      <th>DAY_OF_MONTH</th>\n",
       "      <th>DAY_OF_WEEK</th>\n",
       "      <th>FL_DATE</th>\n",
       "      <th>UNIQUE_CARRIER</th>\n",
       "      <th>ORIGIN</th>\n",
       "      <th>ORIGIN_CITY_NAME</th>\n",
       "      <th>ORIGIN_STATE_ABR</th>\n",
       "      <th>DEST</th>\n",
       "      <th>DEST_CITY_NAME</th>\n",
       "      <th>DEST_STATE_ABR</th>\n",
       "      <th>DEP_TIME</th>\n",
       "      <th>ARR_TIME</th>\n",
       "      <th>ARR_DELAY</th>\n",
       "      <th>AIR_TIME</th>\n",
       "      <th>DISTANCE</th>\n",
       "      <th>DISTANCE_GROUP</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2017</td>\n",
       "      <td>3</td>\n",
       "      <td>7</td>\n",
       "      <td>11</td>\n",
       "      <td>2</td>\n",
       "      <td>7/11/2017</td>\n",
       "      <td>DL</td>\n",
       "      <td>LIT</td>\n",
       "      <td>Little Rock, AR</td>\n",
       "      <td>AR</td>\n",
       "      <td>ATL</td>\n",
       "      <td>Atlanta, GA</td>\n",
       "      <td>GA</td>\n",
       "      <td>538</td>\n",
       "      <td>757</td>\n",
       "      <td>-11.0</td>\n",
       "      <td>64</td>\n",
       "      <td>453</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2018</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>14</td>\n",
       "      <td>3</td>\n",
       "      <td>3/14/2018</td>\n",
       "      <td>DL</td>\n",
       "      <td>BOS</td>\n",
       "      <td>Boston, MA</td>\n",
       "      <td>MA</td>\n",
       "      <td>ATL</td>\n",
       "      <td>Atlanta, GA</td>\n",
       "      <td>GA</td>\n",
       "      <td>1829</td>\n",
       "      <td>2108</td>\n",
       "      <td>-23.0</td>\n",
       "      <td>127</td>\n",
       "      <td>946</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2017</td>\n",
       "      <td>4</td>\n",
       "      <td>11</td>\n",
       "      <td>12</td>\n",
       "      <td>7</td>\n",
       "      <td>11/12/2017</td>\n",
       "      <td>WN</td>\n",
       "      <td>ATL</td>\n",
       "      <td>Atlanta, GA</td>\n",
       "      <td>GA</td>\n",
       "      <td>DAL</td>\n",
       "      <td>Dallas, TX</td>\n",
       "      <td>TX</td>\n",
       "      <td>1345</td>\n",
       "      <td>1451</td>\n",
       "      <td>-9.0</td>\n",
       "      <td>106</td>\n",
       "      <td>721</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2017</td>\n",
       "      <td>3</td>\n",
       "      <td>8</td>\n",
       "      <td>22</td>\n",
       "      <td>2</td>\n",
       "      <td>8/22/2017</td>\n",
       "      <td>EV</td>\n",
       "      <td>ATL</td>\n",
       "      <td>Atlanta, GA</td>\n",
       "      <td>GA</td>\n",
       "      <td>HPN</td>\n",
       "      <td>White Plains, NY</td>\n",
       "      <td>NY</td>\n",
       "      <td>1158</td>\n",
       "      <td>1408</td>\n",
       "      <td>-21.0</td>\n",
       "      <td>113</td>\n",
       "      <td>780</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2018</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>5</td>\n",
       "      <td>3/2/2018</td>\n",
       "      <td>DL</td>\n",
       "      <td>MSY</td>\n",
       "      <td>New Orleans, LA</td>\n",
       "      <td>LA</td>\n",
       "      <td>ATL</td>\n",
       "      <td>Atlanta, GA</td>\n",
       "      <td>GA</td>\n",
       "      <td>522</td>\n",
       "      <td>737</td>\n",
       "      <td>-19.0</td>\n",
       "      <td>59</td>\n",
       "      <td>425</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   YEAR  QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK     FL_DATE UNIQUE_CARRIER  \\\n",
       "0  2017        3      7            11            2   7/11/2017             DL   \n",
       "1  2018        1      3            14            3   3/14/2018             DL   \n",
       "2  2017        4     11            12            7  11/12/2017             WN   \n",
       "3  2017        3      8            22            2   8/22/2017             EV   \n",
       "4  2018        1      3             2            5    3/2/2018             DL   \n",
       "\n",
       "  ORIGIN ORIGIN_CITY_NAME ORIGIN_STATE_ABR DEST    DEST_CITY_NAME  \\\n",
       "0    LIT  Little Rock, AR               AR  ATL       Atlanta, GA   \n",
       "1    BOS       Boston, MA               MA  ATL       Atlanta, GA   \n",
       "2    ATL      Atlanta, GA               GA  DAL        Dallas, TX   \n",
       "3    ATL      Atlanta, GA               GA  HPN  White Plains, NY   \n",
       "4    MSY  New Orleans, LA               LA  ATL       Atlanta, GA   \n",
       "\n",
       "  DEST_STATE_ABR  DEP_TIME  ARR_TIME  ARR_DELAY  AIR_TIME  DISTANCE  \\\n",
       "0             GA       538       757      -11.0        64       453   \n",
       "1             GA      1829      2108      -23.0       127       946   \n",
       "2             TX      1345      1451       -9.0       106       721   \n",
       "3             NY      1158      1408      -21.0       113       780   \n",
       "4             GA       522       737      -19.0        59       425   \n",
       "\n",
       "   DISTANCE_GROUP  \n",
       "0               2  \n",
       "1               4  \n",
       "2               3  \n",
       "3               4  \n",
       "4               2  "
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "zip_file_folder=os.path.join(\"data\")\n",
    "zip_file_path=os.path.join(zip_file_folder,\"Flight Delay Dataset.zip\")\n",
    "print(zip_file_path)\n",
    "with zipfile.ZipFile(zip_file_path,'r') as zip_ref:\n",
    "    with zip_ref.open(\"Flight Delay Dataset.csv\") as csv_file:\n",
    "        df=pd.read_csv(csv_file)\n",
    "        \n",
    "df.head()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "78a33695",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
